### ISSUE TITLE
Hardware back button on android causes app to close

### ISSUE THREAD

**Issue by OneDatSeeSharp** [OneDatSeeSharp/SinTester#1]
This is known bug of the xamarin. Right now I can suspend hardware navigation in whole app to cover this issue.

**Comment by OneDatSeeSharp** [comment]
All navigation suspended.

**Comment by JurekSIN** [comment]
Waiting for the return :)

**Comment by OneDatSeeSharp** [comment]
How do you imagine navigation during test?
 navigate to previous step or navigate to choose substance screen
which screen should be main one?

**Comment by JurekSIN** [comment]
Glowny ekran to powinna byc lista substancji + na samej gorze opcja "Unknown substance". 

Przycisk cofania powinien poprostu cofac do poprzedniego kroku, tak aby niebedac pewnym koloru mozna bylo szybko przeklikac alternatywne scenariusze reakcji.
