### ISSUE TITLE
(After color sorting is done): Enable color error margin

### ISSUE THREAD

**Issue by JurekSIN** [OneDatSeeSharp/SinTester#8]
When we get colors to sort, we can set in options a margin of error.

Let's say we set it at 20% (or a numerical value). All the orange results should be treated sam as red.

**Comment by OneDatSeeSharp** [comment]
Well, this is really huge change, I think it is impossible to implement right now.

**Comment by JurekSIN** [comment]
Is it possible if for example all kinds of yellow would show up, but indeed were treated as the same value, i.e. a single yellow? We would set it manually beforehand, and stwitch on/off in options.
